### ISSUE TITLE
can not detect model type of : unet/iclight_sd15_fc.safetensors

### ISSUE THREAD

**Issue by zhenhua22** [huchenlei/ComfyUI-IC-Light-Native#10]
i can not fix this bug, please ! 
![image](https://github.com/huchenlei/ComfyUI-IC-Light-Native/assets/39483761/612a69d3-7498-423d-b91d-bc94882a3d88)

**Comment by huchenlei** [comment]
Read https://github.com/huchenlei/ComfyUI-IC-Light-Native#download-models.

**Comment by Gavin-Evans** [comment]
@zhenhua22 
ComfyUI-IC-Light-Native 's checkpoint is different from IC-Light-SD-WebUI's, so, need to download right model that @huchenlei has mentioned

**Comment by blue-blue-crystal** [comment]
> Read https://github.com/huchenlei/ComfyUI-IC-Light-Native#download-models.

I followed the instructions on the web page above, and I still get the error in the picture

**Comment by Lucien-Wang123** [comment]
Do you fix it? I have same problem.
