### ISSUE TITLE
IC light can not work even I have installed ComfyUI-layerdiffuse nodes

### ISSUE THREAD

**Issue by zhenhua22** [huchenlei/ComfyUI-IC-Light-Native#11]
what's the reason? How can i fix it.
![image](https://github.com/huchenlei/ComfyUI-IC-Light-Native/assets/39483761/8b2342cf-fae3-446c-a9ae-8afd2b6e580d)

**Comment by huchenlei** [comment]
Please make sure that the input image's width/height and generation latent's width/height are aligned.

**Comment by zhenhua22** [comment]
How can I know my latent's width/height? I know SDv1's latent width/height is  64*64*3. So my input image shape should be 64*64*3?

**Comment by zhenhua22** [comment]
> How can I know my latent's width/height? I know SDv1's latent width/height is 64**64**3. So my input image shape should be 64**64**3?

**Comment by zhenhua22** [comment]
I have solved it! When I load SD1.5 as the base model, it will work.
