### ISSUE TITLE
可能出了一些问题，关于fg.json主体颜色问题。

### ISSUE THREAD

**Issue by newxhy** [huchenlei/ComfyUI-IC-Light-Native#12]
如图：原图的衣服的颜色被去掉了，我并没有对衣服的颜色做过描述
![故障1](https://github.com/huchenlei/ComfyUI-IC-Light-Native/assets/74442467/d33b421d-a736-49b1-9a3c-9b1b008f1682)
![ComfyUI_temp_ooqai_00006_](https://github.com/huchenlei/ComfyUI-IC-Light-Native/assets/74442467/d91e1766-eabc-40ca-9141-61bcc317c711)
![bug](https://github.com/huchenlei/ComfyUI-IC-Light-Native/assets/74442467/99c51ca9-19e1-488b-acf2-63e5d4310740)

**Comment by newxhy** [comment]
我应该是使用了新的IC Light Apply Mask Grey

**Comment by huchenlei** [comment]
Please file the issue in main IC-Light repo. The diffusers impl also has the same issue. https://github.com/lllyasviel/IC-Light/issues
