### ISSUE TITLE
Error occurred when executing KSampler:

### ISSUE THREAD

**Issue by Onionman61** [huchenlei/ComfyUI-IC-Light-Native#18]
'UNetModel' object has no attribute 'default_image_only_indicator'

**Comment by Onionman61** [comment]
![37095b7517bc6fe851e76bf810b7f14](https://github.com/huchenlei/ComfyUI-IC-Light-Native/assets/170847546/5d75a10c-fd12-41d5-85f5-d898f98a7110)
HELP ME please!

**Comment by Onionman61** [comment]
![image](https://github.com/huchenlei/ComfyUI-IC-Light-Native/assets/170847546/2ee52066-4178-43d1-a933-313c1e8bb212)

**Comment by huchenlei** [comment]
Does the error persists if you remove FreeU_Advanced node?

**Comment by Onionman61** [comment]
> 如果删除 FreeU_Advanced 节点，错误是否仍然存在？

it works! thank u!
