### ISSUE TITLE
KSampler error (like everyone else)

### ISSUE THREAD

**Issue by vitalbuttering** [huchenlei/ComfyUI-IC-Light-Native#40]
Installed LayerDiffuse in custom node (like what was recommended), but still getting this error:

KSampler:

Given groups=1, weight of size [320, 12, 3, 3], expected input[2, 8, 96, 64] to have 12 channels, but got 8 channels instead

How do i fix this?

**Comment by vitalbuttering** [comment]
It seems I'm only getting this error when I run sd15_fbc_unet on the load diffusion model. Running fc_unet seems fine...

**Comment by xiaozhelailesz** [comment]
Error occurred when executing KSampler:

Given groups=1, weight of size [320, 4, 3, 3], expected input[2, 8, 64, 64] to have 4 channels, but got 8 channels instead

工作流是作者提供的，layerdiffuse已经安装，模型和节点也是按照作者的工作流设定的，仍然提示错误！

**Comment by xiaozhelailesz** [comment]
使用的是 fc_unet模型

**Comment by gseth** [comment]
This has been fixed, update comfy ui and the node extension to the latest version.

@huchenlei Thanks a lot.

**Comment by vitalbuttering** [comment]
Btw this has been fixed after a ComfyUI update.
