### ISSUE TITLE
Error occurred when executing KSampler: calculate_weight() got an unexpected keyword argument 'intermediate_dtype'

### ISSUE THREAD

**Issue by flybirdxx** [huchenlei/ComfyUI-IC-Light-Native#45]
![image](https://github.com/user-attachments/assets/cfa12a73-63d7-424d-9ea3-3d79d6a836eb)
I'm getting a new error,how do i fix it?

**Comment by huchenlei** [comment]
Fixed by https://github.com/huchenlei/ComfyUI-IC-Light-Native/pull/43
