### ISSUE TITLE
Given groups=1, weight of size [320, 4, 3, 3], expected input[2, 8, 96, 96] to have 4 channels, but got 8 channels instead

### ISSUE THREAD

**Issue by JimWang151** [huchenlei/ComfyUI-IC-Light-Native#49]
很多人有这个问题。

1、ComfyUI是最新的
2、ComfyUI-IC-Light-Native也是最新的
3、ComfyUI-layerdiffuse也是最新的（其中的diffuers>=0.29）
4、ComfyUI-IC-Light也是最新的（我是看其他ISSUE，说这个也得手动更新）
5、两个模型也已经下载并存放到comfyui/models/unet下
6、运行时，选择的checkpoint也是1.5的版本

可运行example里面的workflow时，还是提示“Given groups=1, weight of size [320, 4, 3, 3], expected input[2, 8, 96, 96] to have 4 channels, but got 8 channels instead”

我还有哪里要更新吗？

**Comment by JimWang151** [comment]
我用的samplerCustom解决的问题，关于mask与通道的处理，代码肯定有问题的。

另外，我在ComfyUI-IC-Light中，所有example中的workflow也是没有问题的。

可以肯定的说，关于此类问题，仅更新layerdiffuse应该解决不了所有问题。

给你参考吧，感谢你的辛苦。

**Comment by JimWang151** [comment]
close吧

**Comment by huchenlei** [comment]
After https://github.com/huchenlei/ComfyUI-IC-Light-Native/pull/43, this node pack no longer depends on layerdiffuse custom nodes.
