### ISSUE TITLE
TypeError: calculate_weight() got an unexpected keyword argument 'intermediate_dtype'.

### ISSUE THREAD

**Issue by StableQuestion** [huchenlei/ComfyUI-IC-Light-Native#50]
Problem Description
Workflow Configuration:
I’m using ComfyUI with the Supir Node and IC Light Node.
The workflow also includes the KSampler Adv. (Efficient) node.
Data Precision Settings:
When Supir is set to FP8 precision, everything works fine whether I use IC Light or not.
However, when Supir is set to FP16 or BF16 precision, and IC Light is also used, I encounter an error.
Error Message:
The error message is: TypeError: calculate_weight() got an unexpected keyword argument 'intermediate_dtype'.
Troubleshooting:
Supir works fine in FP16 or BF16 without IC Light.
The error occurs specifically when the workflow reaches the KSampler Adv. (Efficient) node.
Additional Information:
The Supir output goes through additional processing steps before reaching IC Light and the KSampler Adv. (Efficient). These steps should not be causing the issue, but it’s important to note that they are part of the workflow.

Question:
Is there already a known solution or fix for this issue?

**Comment by huchenlei** [comment]
Update your extension and ComfyUI.
