### ISSUE TITLE
Combining FG and BG results in correctly relit FG but the BG is not added back in.

### ISSUE THREAD

**Issue by paulerbear** [huchenlei/ComfyUI-IC-Light-Native#7]
Love your nodes BTW!

[Given FG and BG, Put FG on BG and relight](https://github.com/huchenlei/ComfyUI-IC-Light/blob/main/examples/fg_bg_combine.json)
Combining FG and BG results in correctly relit FG but the BG is not added back in.
![Screenshot 2024-05-12 144023](https://github.com/huchenlei/ComfyUI-IC-Light-Native/assets/145676927/8ba16425-8a59-4ee8-923c-68729b73fd45)

**Comment by huchenlei** [comment]
Thanks for the bug report! Can you attach the input images you used in the workflow so that I can try to reproduce the issue? Thanks again!

**Comment by paulerbear** [comment]
![Untitled design (2)](https://github.com/huchenlei/ComfyUI-IC-Light-Native/assets/145676927/e01cd66a-c4a4-41cd-972f-8806cce383d2)
here you go! 
![Untitled design](https://github.com/huchenlei/ComfyUI-IC-Light-Native/assets/145676927/1e8d67a9-dddb-47b2-89db-bf800298b269)
thanks for your help. they're both 1024 by 768. the same as the input variable in the image resize node.

**Comment by huchenlei** [comment]
Issue confirmed reproducable.
![image](https://github.com/huchenlei/ComfyUI-IC-Light-Native/assets/20929282/e024634c-c4b1-4c1d-9b18-5df236130e45)

However, diffusers version of IC-Light is not having the same issue.
![image](https://github.com/huchenlei/ComfyUI-IC-Light-Native/assets/20929282/01b0826a-4596-4faa-9f0f-2bb277932b3a)

Probably need more investigation

**Comment by huchenlei** [comment]
I added a new node to help convert FG image to IC-Light expected format. 
![image](https://github.com/huchenlei/ComfyUI-IC-Light-Native/assets/20929282/ef89d97a-3ff1-4024-935e-6f09c82149a0)

**Comment by huchenlei** [comment]
Essentially you want the masked area to be grey instead of black when passing it to VAE
![12 05 2024_16 19 02_REC](https://github.com/huchenlei/ComfyUI-IC-Light-Native/assets/20929282/1bd79330-da49-4df2-99b2-d9be70d7bc95)

**Comment by paulerbear** [comment]
Thank you!
