### ISSUE TITLE
这个节点我在ComfyUI的Manager里怎么找不到？

### ISSUE THREAD

**Issue by angelussun** [huchenlei/ComfyUI-IC-Light-Native#9]
安装后模型也有了，怎么用不了呢？
![WX20240514-152200@2x](https://github.com/huchenlei/ComfyUI-IC-Light-Native/assets/17446677/cb854bae-4a1c-4f2a-9df4-2338eaf6d92d)
![WX20240514-152217@2x](https://github.com/huchenlei/ComfyUI-IC-Light-Native/assets/17446677/738cf91a-d37e-4577-8865-b02113310a55)

**Comment by zhenhua22** [comment]
我也遇到这个问题了，你解决了吗？

**Comment by huchenlei** [comment]
Read https://github.com/huchenlei/ComfyUI-IC-Light-Native#download-models. UNETLoader cannot load diffusers format model file.
